name = "hex-matrix"
defaultTargets = ["HexMatrix"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "49d4eb822ce66aa14b18c2472c18848a2411792d"

[[lean_lib]]
name = "HexMatrix"
precompileModules = true
