name = "hex-matrix"
defaultTargets = ["HexMatrix"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "c9cb6bcb3287ea0870f66c9dfcba08baa08f97f6"

[[lean_lib]]
name = "HexMatrix"
precompileModules = true
